name: SpecSync
description: A GitHub-native, frictionless specification system
url: https://github.com/your-org/specsync
hook_attributes:
  url: https://your-domain.com/webhook
  content_type: json
default_permissions:
  contents: read
  pull_requests: write
  issues: write
  metadata: read
default_events:
  - pull_request
  - push
  - issues
  - issue_comment
  - pull_request_review
  - pull_request_review_comment 